/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managevendors;

import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author saravandeepak
 */
public class AtCorpAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ATCorpAdminWorkArea
 
     */
    private JPanel userProcessContainer;
    private VendorCatalog vendorCatalog;

    public AtCorpAdminWorkArea(JPanel userProcessContainer, VendorCatalog vendorCatalog) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vendorCatalog = vendorCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createVendorButton = new javax.swing.JButton();
        manageVendorButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 5));

        createVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        createVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        createVendorButton.setText("Create Vendor");
        createVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVendorButtonActionPerformed(evt);
            }
        });

        manageVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        manageVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        manageVendorButton.setText("Manage Vendor");
        manageVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVendorButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AT Corp Admin Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageVendorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(createVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(manageVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVendorButtonActionPerformed
        // TODO add your handling code here:
        CreateVendorsJPanel panel = new CreateVendorsJPanel(userProcessContainer, vendorCatalog);
        userProcessContainer.add("CreateSupplierPanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_createVendorButtonActionPerformed

    private void manageVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVendorButtonActionPerformed
        // TODO add your handling code here:
        ManageVendorsJPanel panel = new ManageVendorsJPanel(userProcessContainer, vendorCatalog);
        userProcessContainer.add("ManageSupplierPanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_manageVendorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createVendorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageVendorButton;
    // End of variables declaration//GEN-END:variables
}
