/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managevendors;

import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saravandeepak
 */
public class CreateVendorsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVendorsJPanel
     */
    private VendorCatalog vendorCatalog;
    private JPanel userProcessContainer;
    CreateVendorsJPanel(JPanel userProcessContainer, VendorCatalog vendorCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vendorCatalog = vendorCatalog;
    }
    
    public void clearFields(){
        vendorNameText.setText("");
        vendorEmailText.setText("");
        vendorPasswordText.setText("");
        descriptionText.setText("");
        vendorNameText.grabFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createVendorLabel = new javax.swing.JLabel();
        vendorNameLabel = new javax.swing.JLabel();
        vendorNameText = new javax.swing.JTextField();
        supplierDescLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        createButton = new javax.swing.JButton();
        vendorEmailLabel = new javax.swing.JLabel();
        vendorEmailText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        vendorPasswordLabel = new javax.swing.JLabel();
        vendorPasswordText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 5));

        createVendorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        createVendorLabel.setForeground(new java.awt.Color(255, 255, 204));
        createVendorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createVendorLabel.setText("Create Vendor");

        vendorNameLabel.setForeground(new java.awt.Color(255, 255, 204));
        vendorNameLabel.setText("Vendor Name:");

        supplierDescLabel.setForeground(new java.awt.Color(255, 255, 204));
        supplierDescLabel.setText("Vendor Description:");

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        createButton.setBackground(new java.awt.Color(51, 51, 51));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        vendorEmailLabel.setForeground(new java.awt.Color(255, 255, 204));
        vendorEmailLabel.setText("Vendor Email:");

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        vendorPasswordLabel.setForeground(new java.awt.Color(255, 255, 204));
        vendorPasswordLabel.setText("Vendor Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(createButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(supplierDescLabel)
                            .addComponent(vendorNameLabel)
                            .addComponent(vendorEmailLabel)
                            .addComponent(vendorPasswordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(vendorPasswordText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vendorEmailText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vendorNameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(createVendorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(createVendorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorNameLabel)
                    .addComponent(vendorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorEmailLabel)
                    .addComponent(vendorEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorPasswordLabel)
                    .addComponent(vendorPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplierDescLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(vendorNameText.getText().equals("")||vendorEmailText.getText().equals("") || vendorPasswordText.getText().equals("") || descriptionText.getText().equals("")){
        
            JOptionPane.showMessageDialog(this, "Fill all the fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Vendor vendor = new Vendor();
            vendor.setVendorName(vendorNameText.getText());
            vendor.setVendorEmail(vendorEmailText.getText());
            vendor.setVendorPassword(vendorPasswordText.getText());
            vendor.setVendorDescription(descriptionText.getText());
            vendor.setVendorCreatedDate();
            
            vendorCatalog.addVendor(vendor);
            
            JOptionPane.showMessageDialog(this, "Vendor has been created");
            clearFields();
        }
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel createVendorLabel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel supplierDescLabel;
    private javax.swing.JLabel vendorEmailLabel;
    private javax.swing.JTextField vendorEmailText;
    private javax.swing.JLabel vendorNameLabel;
    private javax.swing.JTextField vendorNameText;
    private javax.swing.JLabel vendorPasswordLabel;
    private javax.swing.JTextField vendorPasswordText;
    // End of variables declaration//GEN-END:variables
}
