/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managevendors;

import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saravandeepak
 */
public class ManageVendorsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliers
     */
    private JPanel userProcessContainer;
    private VendorCatalog vendorCatalog;
    ManageVendorsJPanel(JPanel userProcessContainer, VendorCatalog vendorCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vendorCatalog = vendorCatalog;
        populateTable();
    }
    
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)vendorListTable.getModel();
        dtm.setRowCount(0);
        for (Vendor vendor: vendorCatalog.getVendorCatalog()){
            Object[] row = new Object[2];
            row[0] = vendor;
            row[1] = vendor.getVendorEmail();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageVendorHeaderTag = new javax.swing.JLabel();
        VendorListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vendorListTable = new javax.swing.JTable();
        createVendorButton = new javax.swing.JButton();
        viewVendorButton = new javax.swing.JButton();
        updateVendorButton = new javax.swing.JButton();
        searchVendorButton = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 5));
        setForeground(new java.awt.Color(255, 255, 204));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        manageVendorHeaderTag.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        manageVendorHeaderTag.setForeground(new java.awt.Color(255, 255, 204));
        manageVendorHeaderTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageVendorHeaderTag.setText("Manage Vendors");

        VendorListLabel.setForeground(new java.awt.Color(255, 255, 204));
        VendorListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VendorListLabel.setText("Vendors List");

        vendorListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vendorListTable);

        createVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        createVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        createVendorButton.setText("Create Vendor");
        createVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVendorButtonActionPerformed(evt);
            }
        });

        viewVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        viewVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        viewVendorButton.setText("View Vendor");
        viewVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorButtonActionPerformed(evt);
            }
        });

        updateVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        updateVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        updateVendorButton.setText("Update Vendor");
        updateVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVendorButtonActionPerformed(evt);
            }
        });

        searchVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        searchVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        searchVendorButton.setText("Search and View");
        searchVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVendorButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VendorListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageVendorHeaderTag, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(createVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(viewVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(updateVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchVendorButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageVendorHeaderTag, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addComponent(VendorListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchVendorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVendorButtonActionPerformed
        // TODO add your handling code here:
        CreateVendorsJPanel panel = new CreateVendorsJPanel(userProcessContainer, vendorCatalog);
        userProcessContainer.add("CreateSupplierPanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_createVendorButtonActionPerformed

    private void viewVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = vendorListTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            Vendor vendor = (Vendor)vendorListTable.getValueAt(selectedRow,0);
            ViewVendorJPanel panel = new ViewVendorJPanel(userProcessContainer, vendor);
            userProcessContainer.add("ViewSupplierPanel", panel);
            CardLayout card = (CardLayout)userProcessContainer.getLayout();
            card.next(userProcessContainer);
                    
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Please select a row");
        
        }
        
        
    }//GEN-LAST:event_viewVendorButtonActionPerformed

    private void updateVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVendorButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = vendorListTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            Vendor vendor = (Vendor)vendorListTable.getValueAt(selectedRow,0);
            ViewVendorJPanel panel = new ViewVendorJPanel(userProcessContainer, vendor);
            userProcessContainer.add("ViewSupplierPanel", panel);
            CardLayout card = (CardLayout)userProcessContainer.getLayout();
            card.next(userProcessContainer);
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
        
        }
    }//GEN-LAST:event_updateVendorButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_formComponentShown

    private void searchVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVendorButtonActionPerformed
        // TODO add your handling code here:
       if (searchText.getText().equals(""))
       {
          JOptionPane.showMessageDialog(this, "Please enter a Vendor Name to search", "Warning", JOptionPane.WARNING_MESSAGE); 
       }
       else{
           Vendor vendor = vendorCatalog.searchVendor(searchText.getText().toLowerCase());
           if(vendor == null){
                JOptionPane.showMessageDialog(this,"Vendor Name entered does not exist","Information", JOptionPane.INFORMATION_MESSAGE);
            }
           else{
                ViewVendorJPanel panel = new ViewVendorJPanel(userProcessContainer, vendor);
                userProcessContainer.add("ViewSupplierPanel", panel);
                CardLayout card = (CardLayout)userProcessContainer.getLayout();
                card.next(userProcessContainer);
            }
       }
    }//GEN-LAST:event_searchVendorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VendorListLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createVendorButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageVendorHeaderTag;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton searchVendorButton;
    private javax.swing.JButton updateVendorButton;
    private javax.swing.JTable vendorListTable;
    private javax.swing.JButton viewVendorButton;
    // End of variables declaration//GEN-END:variables
}
