/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.University;
import business.college.College;
import business.college.department.student.Student;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author nithinkartha
 */
public class UniversityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UniversityJPanel
     */
    private JPanel userContainerJPanel;
    private University university;

    public UniversityJPanel(JPanel userContainerJPanel, University university) {
        initComponents();
        this.university = university;
        this.userContainerJPanel = userContainerJPanel;
        populateTable();
        universityNameLabel.setText(this.university.getUniversityName());
    }

    private void populateTable() {
        DefaultTableModel dTM = (DefaultTableModel) tblCollege.getModel();
        dTM.setRowCount(0);
        for (College college : this.university.getCollegeList()) {
            Object row[] = new Object[1];
            row[0] = college;

            dTM.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCollege = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        universityNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        tblCollege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                           College Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCollege);
        if (tblCollege.getColumnModel().getColumnCount() > 0) {
            tblCollege.getColumnModel().getColumn(0).setResizable(false);
        }

        btnView.setText("View College Details>>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnGenerate.setText("Generate University Report");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        universityNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        universityNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        universityNameLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(universityNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btnGenerate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(universityNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        generateSpecificUniversityReport(this.university);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userContainerJPanel.remove(this);
        CardLayout layout = (CardLayout) userContainerJPanel.getLayout();
        layout.previous(userContainerJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
                int selectedRow = tblCollege.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please Select a Row", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            College college = (College) tblCollege.getValueAt(selectedRow, 0);

            CollegeJPanel panel = new CollegeJPanel(userContainerJPanel, college);
            userContainerJPanel.add("CollegeJPanel", panel);
            CardLayout layout = (CardLayout) userContainerJPanel.getLayout();
            layout.next(userContainerJPanel);

        }
        
    }//GEN-LAST:event_btnViewActionPerformed
    public void generateSpecificUniversityReport(University university){
        XSSFWorkbook xcel = new XSSFWorkbook();
        XSSFSheet sheet =  xcel.createSheet("University details");
        
        XSSFCellStyle headerStyle = xcel.createCellStyle();
        XSSFFont font = xcel.createFont();
        font.setBold(true);
        headerStyle.setFont(font);
        
        XSSFRow headerRow = sheet.createRow(0); 
        XSSFCell headerCell1 = headerRow.createCell(0);
        headerCell1.setCellValue("University Name");
        headerCell1.setCellStyle(headerStyle);
        XSSFCell headerCell2 = headerRow.createCell(1);
        headerCell2.setCellValue("University Revenue");
        headerCell2.setCellStyle(headerStyle);
        XSSFCell headerCell3 = headerRow.createCell(2);
        headerCell3.setCellValue("Number of Colleges");
        headerCell3.setCellStyle(headerStyle);
        XSSFCell headerCell4 = headerRow.createCell(3);
        headerCell4.setCellValue("Employment Rate %");
        headerCell4.setCellStyle(headerStyle);
        XSSFCell headerCell5 = headerRow.createCell(4);
        headerCell5.setCellValue("University Profit/Loss");
        headerCell5.setCellStyle(headerStyle);
        XSSFCell headerCell6 = headerRow.createCell(5);
        headerCell6.setCellValue("University Faculty Strength");
        headerCell6.setCellStyle(headerStyle);
        XSSFCell headerCell7 = headerRow.createCell(6);
        headerCell7.setCellValue("University Staff Strength");
        headerCell7.setCellStyle(headerStyle);
        XSSFCell headerCell8 = headerRow.createCell(7);
        headerCell8.setCellValue("University Total Employee Count");
        headerCell8.setCellStyle(headerStyle);
        
        XSSFRow row = sheet.createRow(1); 
        XSSFCell cell = row.createCell(0);
        cell.setCellValue(university.getUniversityName());
        XSSFCell cell1 = row.createCell(1);
        cell1.setCellValue(university.calculateUniversityRevenue());
        XSSFCell cell2 = row.createCell(2);
        cell2.setCellValue(university.getCollegeList().size());
        XSSFCell cell3 = row.createCell(3);
        cell3.setCellValue(university.getEmploymentRate());
        XSSFCell cell4 = row.createCell(4);
        cell4.setCellValue(university.calculateUniversityProfitLoss());
        XSSFCell cell5 = row.createCell(5);
        cell5.setCellValue(university.calculateUniFacultyStrength());
        XSSFCell cell6 = row.createCell(6);
        cell6.setCellValue(university.calculateUniStaffStrength());
        XSSFCell cell7 = row.createCell(7);
        cell7.setCellValue(university.calculateNumberOfUniversityEmployees());
        
        XSSFSheet sheet4 =  xcel.createSheet("Student Details");

        XSSFRow headerSRow = sheet4.createRow(0); 
        XSSFCell headerSCell1 = headerSRow.createCell(0);
        headerSCell1.setCellValue("First Name");
        headerSCell1.setCellStyle(headerStyle);
        XSSFCell headerSCell2 = headerSRow.createCell(1);
        headerSCell2.setCellValue("Last Name");
        headerSCell2.setCellStyle(headerStyle);
        XSSFCell headerSCell3 = headerSRow.createCell(2);
        headerSCell3.setCellValue("Student Id");
        headerSCell3.setCellStyle(headerStyle);
        XSSFCell headerSCell4 = headerSRow.createCell(3);
        headerSCell4.setCellValue("Email");
        headerSCell4.setCellStyle(headerStyle);
        XSSFCell headerSCell5 = headerSRow.createCell(4);
        headerSCell5.setCellValue("Nationality");
        headerSCell5.setCellStyle(headerStyle);
        XSSFCell headerSCell6 = headerSRow.createCell(5);
        headerSCell6.setCellValue("Tuition Expense");
        headerSCell6.setCellStyle(headerStyle);
        int i= 1;
        for(Student student: university.getUniversityStudentDirectory()){
       
            XSSFRow sRow = sheet4.createRow(i); 
            XSSFCell sCell1 = sRow.createCell(0);
            sCell1.setCellValue(student.getFirstName());
            XSSFCell sCell2 = sRow.createCell(1);
            sCell2.setCellValue(student.getLastName());
            XSSFCell sCell3 = sRow.createCell(2);
            sCell3.setCellValue(student.getNuid());
            XSSFCell sCell4 = sRow.createCell(3);
            sCell4.setCellValue(student.getEmail());
            XSSFCell sCell5 = sRow.createCell(4);
            sCell5.setCellValue(student.getNationality());
            XSSFCell sCell6 = sRow.createCell(5);
            sCell6.setCellValue(student.getTuitionExpense());
            i++;
        }
        
        try
        {
            try ( //Write the workbook in file system
                    FileOutputStream out = new FileOutputStream(new File(university.getUniversityName()+"_universityReport.xlsx"))) {
                    xcel.write(out);
                    JOptionPane.showMessageDialog(this, "University Report has been created. Check your project folder for " + university.getUniversityName()+"_universityReport.xlsx");

            }
            System.out.println(university.getUniversityName()+"_universityreport.xlsx written successfully on disk.");
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCollege;
    private javax.swing.JLabel universityNameLabel;
    // End of variables declaration//GEN-END:variables
}
