/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
import business.ResumeHistory;
/**
 *
 * @author saravandeepak
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private ResumeHistory resumeHistory;
    public MainJFrame() {
        initComponents();
        resumeHistory = new ResumeHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResumeSplitPane = new javax.swing.JSplitPane();
        splitLeftPanel = new javax.swing.JPanel();
        splitRightPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(745, 670));
        setPreferredSize(new java.awt.Dimension(765, 700));

        ResumeSplitPane.setBackground(new java.awt.Color(255, 255, 255));
        ResumeSplitPane.setMinimumSize(new java.awt.Dimension(765, 670));
        ResumeSplitPane.setPreferredSize(new java.awt.Dimension(765, 670));

        splitLeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        splitLeftPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        splitLeftPanel.setPreferredSize(new java.awt.Dimension(665, 650));

        javax.swing.GroupLayout splitLeftPanelLayout = new javax.swing.GroupLayout(splitLeftPanel);
        splitLeftPanel.setLayout(splitLeftPanelLayout);
        splitLeftPanelLayout.setHorizontalGroup(
            splitLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        splitLeftPanelLayout.setVerticalGroup(
            splitLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        ResumeSplitPane.setRightComponent(splitLeftPanel);

        splitRightPanel.setBackground(new java.awt.Color(62, 39, 35));
        splitRightPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        createButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        createButton.setForeground(new java.awt.Color(0, 51, 102));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        displayButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        displayButton.setForeground(new java.awt.Color(0, 51, 102));
        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout splitRightPanelLayout = new javax.swing.GroupLayout(splitRightPanel);
        splitRightPanel.setLayout(splitRightPanelLayout);
        splitRightPanelLayout.setHorizontalGroup(
            splitRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        splitRightPanelLayout.setVerticalGroup(
            splitRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(splitRightPanelLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(displayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        ResumeSplitPane.setLeftComponent(splitRightPanel);

        getContentPane().add(ResumeSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        CreateJPanel createJPanel = new CreateJPanel(resumeHistory); 
        ResumeSplitPane.setRightComponent(createJPanel);        // TODO add your handling code here:

    }//GEN-LAST:event_createButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        // TODO add your handling code here:
        DisplayJPanel displayJPanel = new DisplayJPanel(resumeHistory); 
        ResumeSplitPane.setRightComponent(displayJPanel);
    }//GEN-LAST:event_displayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane ResumeSplitPane;
    private javax.swing.JButton createButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JPanel splitLeftPanel;
    private javax.swing.JPanel splitRightPanel;
    // End of variables declaration//GEN-END:variables
}
