/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.manageproducts;

import business.ProductMasterCatalog;
import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saravandeepak
 */
public class VendorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form VendorWorkArea
     */
    private VendorCatalog vendorCatalog;
    private ProductMasterCatalog productCatalog;
    private JPanel userProcessContainer;
    private Vendor vendor;
    public VendorWorkArea(JPanel userProcessContainer, VendorCatalog vendorCatalog, ProductMasterCatalog productCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vendorCatalog = vendorCatalog;
        this.productCatalog = productCatalog;
        manageProductButton.setVisible(false);
        populateVendorComboBox();
        
        //vendorListComboBox.addItem("Panic");
    }
    
    public void populateVendorComboBox(){
        for (Vendor vendor: vendorCatalog.getVendorCatalog() ){
            vendorListComboBox.addItem(vendor.toString());
        }
    }

    public Vendor validateVendor(String vendorName){
        for(Vendor vendor: vendorCatalog.getVendorCatalog()){
            if(vendor.getVendorName().equals(vendorName)){
                return vendor;
            }
                
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vendorLabel = new javax.swing.JLabel();
        vendorListComboBox = new javax.swing.JComboBox<>();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        vendorPasswordField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        manageProductButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        vendorLabel.setForeground(new java.awt.Color(255, 255, 204));
        vendorLabel.setText("Vendor Name:");

        passwordLabel.setForeground(new java.awt.Color(255, 255, 204));
        passwordLabel.setText("Password:");

        loginButton.setBackground(new java.awt.Color(51, 51, 51));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        manageProductButton.setBackground(new java.awt.Color(51, 51, 51));
        manageProductButton.setForeground(new java.awt.Color(255, 255, 255));
        manageProductButton.setText("Manage Products");
        manageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(vendorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton)
                    .addComponent(vendorListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(manageProductButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorLabel)
                    .addComponent(vendorListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(vendorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(loginButton)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(manageProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String vendorUser = vendorListComboBox.getSelectedItem().toString();
        String pass = new String(vendorPasswordField.getPassword());
        vendor = validateVendor(vendorUser);
        if(vendor == null){
            JOptionPane.showMessageDialog(this, "No User");
        }
        else{
            if(vendor.getVendorPassword().equals(pass)){
                JOptionPane.showMessageDialog(this, "Login Successfull");
                manageProductButton.setVisible(true); 
                vendorListComboBox.setEnabled(false);
                vendorPasswordField.setEnabled(false);
                loginButton.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Wrong Password");
            }
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void manageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductButtonActionPerformed
        // TODO add your handling code here:
        ManageProductsJPanel panel = new ManageProductsJPanel(userProcessContainer, productCatalog, vendor);
        userProcessContainer.add("ManageProductsPanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_manageProductButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        vendorListComboBox.setEnabled(true);
        vendorPasswordField.setEnabled(true);
        vendorPasswordField.setText("");
        loginButton.setEnabled(true);
        manageProductButton.setVisible(false);
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton manageProductButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JComboBox<String> vendorListComboBox;
    private javax.swing.JPasswordField vendorPasswordField;
    // End of variables declaration//GEN-END:variables
}
