/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.manageproducts;

import business.ProductMaster;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author saravandeepak
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductJPanel
     */
    private JPanel userProcessContainer;
    private ProductMaster product;
    private Image image;
    ViewProductJPanel(JPanel userProcessContainer, ProductMaster product) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.product = product;
        setFieldsonLoad();
        productNameText.setText(product.getProductName());
        modelNoText.setText(product.getModelNo());
        descriptionText.setText(product.getProductDescription());
        featuresText.setText(product.getProductFeatures());
        switch (product.getProductCategory()) {
            case "Computer":
                categoryButtonGroup.setSelected(computerRb.getModel(), true);
                break;
            case "Printer":
                categoryButtonGroup.setSelected(printerRb.getModel(), true);
                break;
            case "Hardware Product":
                categoryButtonGroup.setSelected(hardwareRb.getModel(), true);
                break;
            case "Software Product":
                categoryButtonGroup.setSelected(softwareRb.getModel(), true);
                break;
            default:
                break;
        }
        basePriceText.setText(String.valueOf(product.getBasePrice()));
        ceilingPriceText.setText(String.valueOf(product.getCeilingPrice()));
        floorPriceText.setText(String.valueOf(product.getFloorPrice()));
        
        otherInfoText.setText(product.getOtherInfo());
        vendorNameText.setText(product.getVendorName());
        try{
            pictureLabel.setIcon(new ImageIcon(product.getProductImg()));
        }
        catch(Exception e){
            
        }
        
    }
    
    public void setFieldsonLoad(){
        productNameText.setEnabled(false);
        modelNoText.setEnabled(false);
        descriptionText.setEnabled(false);
        featuresText.setEnabled(false);
        computerRb.setEnabled(false);
        printerRb.setEnabled(false);
        hardwareRb.setEnabled(false);
        softwareRb.setEnabled(false);
        basePriceText.setEnabled(false);
        ceilingPriceText.setEnabled(false);
        floorPriceText.setEnabled(false);
        otherInfoText.setEnabled(false);
        saveButton.setEnabled(false);
        updateButton.setEnabled(true);
        
    }
    public void setFieldsOnUpdate(){
        productNameText.setEnabled(true);
        modelNoText.setEnabled(true);
        descriptionText.setEnabled(true);
        featuresText.setEnabled(true);
        computerRb.setEnabled(true);
        printerRb.setEnabled(true);
        hardwareRb.setEnabled(true);
        softwareRb.setEnabled(true);
        basePriceText.setEnabled(true);
        ceilingPriceText.setEnabled(true);
        floorPriceText.setEnabled(true);
        otherInfoText.setEnabled(true);
        saveButton.setEnabled(true);
        updateButton.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryButtonGroup = new javax.swing.ButtonGroup();
        categoryLabel = new javax.swing.JLabel();
        otherInfoLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        otherInfoText = new javax.swing.JTextArea();
        pictureLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        featuresText = new javax.swing.JTextArea();
        productNameLabel = new javax.swing.JLabel();
        productNameText = new javax.swing.JTextField();
        modelNoLabel = new javax.swing.JLabel();
        modelNoText = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        featuresLabel = new javax.swing.JLabel();
        viewProductHeadTag = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        vendorNameLabel = new javax.swing.JLabel();
        vendorNameText = new javax.swing.JTextField();
        computerRb = new javax.swing.JRadioButton();
        printerRb = new javax.swing.JRadioButton();
        hardwareRb = new javax.swing.JRadioButton();
        softwareRb = new javax.swing.JRadioButton();
        basePriceLabel = new javax.swing.JLabel();
        basePriceText = new javax.swing.JTextField();
        ceilingPriceLabel = new javax.swing.JLabel();
        dollar1Label = new javax.swing.JLabel();
        ceilingPriceText = new javax.swing.JTextField();
        dollar2Label = new javax.swing.JLabel();
        floorPriceLabel = new javax.swing.JLabel();
        floorPriceText = new javax.swing.JTextField();
        dollar3Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 5));

        categoryLabel.setForeground(new java.awt.Color(255, 255, 204));
        categoryLabel.setText("Category:");

        otherInfoLabel.setForeground(new java.awt.Color(255, 255, 204));
        otherInfoLabel.setText("<html>Other Information:<br>(Warranty, <br>Terms of use,<br>etc.)<html>");

        otherInfoText.setColumns(20);
        otherInfoText.setRows(5);
        jScrollPane4.setViewportView(otherInfoText);

        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setText("Picture");
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        featuresText.setColumns(20);
        featuresText.setRows(5);
        jScrollPane2.setViewportView(featuresText);

        productNameLabel.setForeground(new java.awt.Color(255, 255, 204));
        productNameLabel.setText("Product Name:");

        modelNoLabel.setForeground(new java.awt.Color(255, 255, 204));
        modelNoLabel.setText("Model Number");

        descriptionLabel.setForeground(new java.awt.Color(255, 255, 204));
        descriptionLabel.setText("Product Description:");

        featuresLabel.setForeground(new java.awt.Color(255, 255, 204));
        featuresLabel.setText("Product Features:");

        viewProductHeadTag.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        viewProductHeadTag.setForeground(new java.awt.Color(255, 255, 204));
        viewProductHeadTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewProductHeadTag.setText("View Product Details");

        saveButton.setBackground(new java.awt.Color(51, 51, 51));
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(51, 51, 51));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        vendorNameLabel.setForeground(new java.awt.Color(255, 255, 204));
        vendorNameLabel.setText("Vendor Name:");

        vendorNameText.setEnabled(false);

        categoryButtonGroup.add(computerRb);
        computerRb.setForeground(new java.awt.Color(255, 255, 204));
        computerRb.setText("Computer");

        categoryButtonGroup.add(printerRb);
        printerRb.setForeground(new java.awt.Color(255, 255, 204));
        printerRb.setText("Printer");

        categoryButtonGroup.add(hardwareRb);
        hardwareRb.setForeground(new java.awt.Color(255, 255, 204));
        hardwareRb.setText("Hardware Product");

        categoryButtonGroup.add(softwareRb);
        softwareRb.setForeground(new java.awt.Color(255, 255, 204));
        softwareRb.setText("Software Product");

        basePriceLabel.setForeground(new java.awt.Color(255, 255, 204));
        basePriceLabel.setText("Base Price:");

        ceilingPriceLabel.setForeground(new java.awt.Color(255, 255, 204));
        ceilingPriceLabel.setText("Ceiling Price:");

        dollar1Label.setForeground(new java.awt.Color(255, 255, 204));
        dollar1Label.setText("$");

        dollar2Label.setForeground(new java.awt.Color(255, 255, 204));
        dollar2Label.setText("$");

        floorPriceLabel.setForeground(new java.awt.Color(255, 255, 204));
        floorPriceLabel.setText("Floor Price:");

        floorPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorPriceTextActionPerformed(evt);
            }
        });

        dollar3Label.setForeground(new java.awt.Color(255, 255, 204));
        dollar3Label.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewProductHeadTag, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(saveButton)
                .addGap(26, 26, 26)
                .addComponent(updateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(featuresLabel)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(modelNoLabel)
                                    .addComponent(productNameLabel)
                                    .addComponent(vendorNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vendorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(categoryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(computerRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printerRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hardwareRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(softwareRb)))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(otherInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(basePriceLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(basePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(dollar1Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ceilingPriceLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ceilingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(dollar2Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(floorPriceLabel)
                                        .addGap(0, 0, 0)
                                        .addComponent(floorPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(dollar3Label))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewProductHeadTag, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNameLabel)
                            .addComponent(productNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelNoLabel)
                            .addComponent(modelNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorNameLabel)
                            .addComponent(vendorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(computerRb)
                    .addComponent(printerRb)
                    .addComponent(hardwareRb)
                    .addComponent(softwareRb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basePriceLabel)
                    .addComponent(basePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar1Label)
                    .addComponent(ceilingPriceLabel)
                    .addComponent(ceilingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar2Label)
                    .addComponent(floorPriceLabel)
                    .addComponent(floorPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollar3Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featuresLabel)
                    .addComponent(descriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(updateButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        product.setProductName(productNameText.getText());
        product.setModelNo(modelNoText.getText());
        product.setProductDescription(descriptionText.getText());
        product.setProductFeatures(featuresText.getText());
        try{
            product.setBasePrice(Double.parseDouble(basePriceText.getText()));
            product.setCeilingPrice(Double.parseDouble(ceilingPriceText.getText()));
            product.setFloorPrice(Double.parseDouble(floorPriceText.getText()));
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Price can be only numbers below 999,999", "Error", JOptionPane.ERROR_MESSAGE); 
                basePriceText.grabFocus();
                return;
            }
            if(basePriceText.getText().length()>6 || ceilingPriceText.getText().length()>6 || floorPriceText.getText().length()>6){
                JOptionPane.showMessageDialog(this, "Max price can only be 999,999! We don't deal with millions worth products","Warning",JOptionPane.WARNING_MESSAGE);
                basePriceText.grabFocus();
                return;
            }
            if(Double.parseDouble(basePriceText.getText()) < Double.parseDouble(floorPriceText.getText()) || Double.parseDouble(ceilingPriceText.getText()) < Double.parseDouble(basePriceText.getText())) {
                JOptionPane.showMessageDialog(this, "Ceiling Price >= Base Price >= Floor Price","Warning",JOptionPane.WARNING_MESSAGE);
                basePriceText.grabFocus();
                return;
            }
        product.setOtherInfo(otherInfoText.getText());
        //product.setProductImg(image);
        if(computerRb.isSelected()){
            product.setProductCategory(computerRb.getText());
        }
        else if(printerRb.isSelected()){
            product.setProductCategory(printerRb.getText());
        }
        else if(hardwareRb.isSelected()){
            product.setProductCategory(hardwareRb.getText());
        }
        else if(softwareRb.isSelected()){
            product.setProductCategory(softwareRb.getText());
        }
        setFieldsonLoad();
 
        JOptionPane.showMessageDialog(this, "Product has been saved");
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        setFieldsOnUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void floorPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorPriceTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel basePriceLabel;
    private javax.swing.JTextField basePriceText;
    private javax.swing.ButtonGroup categoryButtonGroup;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel ceilingPriceLabel;
    private javax.swing.JTextField ceilingPriceText;
    private javax.swing.JRadioButton computerRb;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JLabel dollar1Label;
    private javax.swing.JLabel dollar2Label;
    private javax.swing.JLabel dollar3Label;
    private javax.swing.JLabel featuresLabel;
    private javax.swing.JTextArea featuresText;
    private javax.swing.JLabel floorPriceLabel;
    private javax.swing.JTextField floorPriceText;
    private javax.swing.JRadioButton hardwareRb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel modelNoLabel;
    private javax.swing.JTextField modelNoText;
    private javax.swing.JLabel otherInfoLabel;
    private javax.swing.JTextArea otherInfoText;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JRadioButton printerRb;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameText;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton softwareRb;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel vendorNameLabel;
    private javax.swing.JTextField vendorNameText;
    private javax.swing.JLabel viewProductHeadTag;
    // End of variables declaration//GEN-END:variables
}
