/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.ProductMaster;
import business.Vendor;
import business.VendorCatalog;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saravandeepak
 */
public class CustomerViewProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerViewProductsJPanel
     */
    private JPanel userProcessContainer;
    private ProductMaster product;
    private VendorCatalog vendorCatalog;

    CustomerViewProductsJPanel(JPanel userProcessContainer, ProductMaster product, VendorCatalog vendorCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.product = product;
        this.vendorCatalog = vendorCatalog;
        setFields();
    }
    
    public void setFields(){
        productNameText.setText(product.getProductName());
        modelNoText.setText(product.getModelNo());
        descriptionText.setText(product.getProductDescription());
        featuresText.setText(product.getProductFeatures());
        categoryText.setText(product.getProductCategory());
        basePriceText.setText(String.valueOf(product.getBasePrice()));
        otherInfoText.setText(product.getOtherInfo());
        vendorNameText.setText(product.getVendorName());
        try{
            pictureLabel.setIcon(new ImageIcon(product.getProductImg()));
        }
        catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        otherInfoLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        otherInfoText = new javax.swing.JTextArea();
        pictureLabel = new javax.swing.JLabel();
        dollar1Label = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        basePriceText = new javax.swing.JTextField();
        featuresLabel = new javax.swing.JLabel();
        basePriceLabel = new javax.swing.JLabel();
        viewProductHeadTag = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        featuresText = new javax.swing.JTextArea();
        vendorNameLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        vendorNameText = new javax.swing.JTextField();
        productNameText = new javax.swing.JTextField();
        modelNoLabel = new javax.swing.JLabel();
        modelNoText = new javax.swing.JTextField();
        categoryText = new javax.swing.JTextField();
        viewVendorButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        otherInfoLabel.setForeground(new java.awt.Color(255, 255, 204));
        otherInfoLabel.setText("<html>Other Information:<br>(Warranty, <br>Terms of use,<br>etc.)<html>");

        otherInfoText.setEditable(false);
        otherInfoText.setColumns(20);
        otherInfoText.setLineWrap(true);
        otherInfoText.setRows(5);
        jScrollPane4.setViewportView(otherInfoText);

        pictureLabel.setForeground(new java.awt.Color(255, 255, 204));
        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setText("Picture");
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dollar1Label.setForeground(new java.awt.Color(255, 255, 204));
        dollar1Label.setText("$");

        descriptionLabel.setForeground(new java.awt.Color(255, 255, 204));
        descriptionLabel.setText("Product Description:");

        basePriceText.setEditable(false);

        featuresLabel.setForeground(new java.awt.Color(255, 255, 204));
        featuresLabel.setText("Product Features:");

        basePriceLabel.setForeground(new java.awt.Color(255, 255, 204));
        basePriceLabel.setText("Base Price:");

        viewProductHeadTag.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        viewProductHeadTag.setForeground(new java.awt.Color(255, 255, 204));
        viewProductHeadTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewProductHeadTag.setText("View Product Details");

        categoryLabel.setForeground(new java.awt.Color(255, 255, 204));
        categoryLabel.setText("Category:");

        descriptionText.setEditable(false);
        descriptionText.setColumns(20);
        descriptionText.setLineWrap(true);
        descriptionText.setRows(5);
        jScrollPane1.setViewportView(descriptionText);

        featuresText.setEditable(false);
        featuresText.setColumns(20);
        featuresText.setLineWrap(true);
        featuresText.setRows(5);
        jScrollPane2.setViewportView(featuresText);

        vendorNameLabel.setForeground(new java.awt.Color(255, 255, 204));
        vendorNameLabel.setText("Vendor Name:");

        productNameLabel.setForeground(new java.awt.Color(255, 255, 204));
        productNameLabel.setText("Product Name:");

        vendorNameText.setEditable(false);
        vendorNameText.setEnabled(false);

        productNameText.setEditable(false);

        modelNoLabel.setForeground(new java.awt.Color(255, 255, 204));
        modelNoLabel.setText("Model Number");

        modelNoText.setEditable(false);

        categoryText.setEditable(false);
        categoryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextActionPerformed(evt);
            }
        });

        viewVendorButton.setBackground(new java.awt.Color(51, 51, 51));
        viewVendorButton.setForeground(new java.awt.Color(255, 255, 255));
        viewVendorButton.setText("View vendor Details");
        viewVendorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewProductHeadTag, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(otherInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(featuresLabel)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelNoLabel)
                            .addComponent(productNameLabel)
                            .addComponent(basePriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(basePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dollar1Label))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vendorNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vendorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewVendorButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewProductHeadTag, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productNameLabel)
                            .addComponent(productNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelNoLabel)
                            .addComponent(modelNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(basePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dollar1Label)
                            .addComponent(basePriceLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vendorNameLabel)
                    .addComponent(viewVendorButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(featuresLabel)
                    .addComponent(descriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void categoryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTextActionPerformed

    private void viewVendorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorButtonActionPerformed
        // TODO add your handling code here:
        Vendor vendor  = vendorCatalog.searchVendor(vendorNameText.getText());
        
        
        JOptionPane.showMessageDialog(this, new Object[]{"Vendor Name: " + vendor.getVendorName(), "Vendor Email: " + vendor.getVendorEmail(), "Vendor Description: " + vendor.getVendorDescription()}, "Vendor Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_viewVendorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel basePriceLabel;
    private javax.swing.JTextField basePriceText;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField categoryText;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JLabel dollar1Label;
    private javax.swing.JLabel featuresLabel;
    private javax.swing.JTextArea featuresText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel modelNoLabel;
    private javax.swing.JTextField modelNoText;
    private javax.swing.JLabel otherInfoLabel;
    private javax.swing.JTextArea otherInfoText;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productNameText;
    private javax.swing.JLabel vendorNameLabel;
    private javax.swing.JTextField vendorNameText;
    private javax.swing.JLabel viewProductHeadTag;
    private javax.swing.JButton viewVendorButton;
    // End of variables declaration//GEN-END:variables
}
