/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.customer;

import business.ProductMaster;
import business.ProductMasterCatalog;
import business.VendorCatalog;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saravandeepak
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ProductMasterCatalog productCatalog;
    private VendorCatalog vendorCatalog;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, ProductMasterCatalog productCatalog, VendorCatalog vendorCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productCatalog = productCatalog;
        this.vendorCatalog = vendorCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerTag = new javax.swing.JLabel();
        productSearchText = new javax.swing.JTextField();
        searchProductsButton = new javax.swing.JButton();
        catalogsHeadertag = new javax.swing.JLabel();
        browseComputerButton = new javax.swing.JButton();
        browsePrinterButton = new javax.swing.JButton();
        browseHardwareButton = new javax.swing.JButton();
        browseSoftwareButton = new javax.swing.JButton();
        browseAllProductsButton = new javax.swing.JButton();
        searchProductsLabel = new javax.swing.JLabel();
        subHeaderTag = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 5));

        headerTag.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        headerTag.setForeground(new java.awt.Color(255, 255, 204));
        headerTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerTag.setText("Welcome to ATCorp ");

        searchProductsButton.setBackground(new java.awt.Color(51, 51, 51));
        searchProductsButton.setForeground(new java.awt.Color(255, 255, 255));
        searchProductsButton.setText("Search Products");
        searchProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductsButtonActionPerformed(evt);
            }
        });

        catalogsHeadertag.setForeground(new java.awt.Color(255, 255, 204));
        catalogsHeadertag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catalogsHeadertag.setText("We Have four Product Catalogs. Browse through them to look at the products.");

        browseComputerButton.setBackground(new java.awt.Color(255, 255, 255));
        browseComputerButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        browseComputerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/customer/computer.jpg"))); // NOI18N
        browseComputerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseComputerButtonActionPerformed(evt);
            }
        });

        browsePrinterButton.setBackground(new java.awt.Color(255, 255, 255));
        browsePrinterButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        browsePrinterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/customer/printer.jpg"))); // NOI18N
        browsePrinterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsePrinterButtonActionPerformed(evt);
            }
        });

        browseHardwareButton.setBackground(new java.awt.Color(255, 255, 255));
        browseHardwareButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        browseHardwareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/customer/hardware.jpg"))); // NOI18N
        browseHardwareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseHardwareButtonActionPerformed(evt);
            }
        });

        browseSoftwareButton.setBackground(new java.awt.Color(255, 255, 255));
        browseSoftwareButton.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        browseSoftwareButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/customer/software.jpg"))); // NOI18N
        browseSoftwareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseSoftwareButtonActionPerformed(evt);
            }
        });

        browseAllProductsButton.setBackground(new java.awt.Color(255, 255, 255));
        browseAllProductsButton.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        browseAllProductsButton.setForeground(new java.awt.Color(102, 0, 0));
        browseAllProductsButton.setText("Browse All");
        browseAllProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseAllProductsButtonActionPerformed(evt);
            }
        });

        searchProductsLabel.setForeground(new java.awt.Color(255, 255, 204));
        searchProductsLabel.setText("Search any Product:");

        subHeaderTag.setForeground(new java.awt.Color(255, 255, 204));
        subHeaderTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subHeaderTag.setText("Find all your needs in one stop !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catalogsHeadertag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subHeaderTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browseHardwareButton)
                    .addComponent(browseComputerButton))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(browseSoftwareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(browsePrinterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchProductsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(browseAllProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(headerTag, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subHeaderTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProductsButton)
                    .addComponent(searchProductsLabel))
                .addGap(18, 18, 18)
                .addComponent(catalogsHeadertag, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseComputerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsePrinterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browseSoftwareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseHardwareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(browseAllProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browsePrinterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsePrinterButtonActionPerformed
        // TODO add your handling code here:
        CustomerBrowseJPanel panel = new CustomerBrowseJPanel(userProcessContainer, productCatalog, "Printer", vendorCatalog);
        userProcessContainer.add("CustomerBrowsePanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_browsePrinterButtonActionPerformed

    private void browseComputerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseComputerButtonActionPerformed
        // TODO add your handling code here:
        CustomerBrowseJPanel panel = new CustomerBrowseJPanel(userProcessContainer, productCatalog, "Computer", vendorCatalog);
        userProcessContainer.add("CustomerBrowsePanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_browseComputerButtonActionPerformed

    private void browseSoftwareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseSoftwareButtonActionPerformed
        // TODO add your handling code here:
        CustomerBrowseJPanel panel = new CustomerBrowseJPanel(userProcessContainer, productCatalog, "Software Product", vendorCatalog);
        userProcessContainer.add("CustomerBrowsePanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_browseSoftwareButtonActionPerformed

    private void browseHardwareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseHardwareButtonActionPerformed
        // TODO add your handling code here:
        CustomerBrowseJPanel panel = new CustomerBrowseJPanel(userProcessContainer, productCatalog, "Hardware Product", vendorCatalog);
        userProcessContainer.add("CustomerBrowsePanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_browseHardwareButtonActionPerformed

    private void browseAllProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseAllProductsButtonActionPerformed
        // TODO add your handling code here:
        CustomerBrowseJPanel panel = new CustomerBrowseJPanel(userProcessContainer, productCatalog, "All", vendorCatalog);
        userProcessContainer.add("CustomerBrowsePanel", panel);
        CardLayout card = (CardLayout)userProcessContainer.getLayout();
        card.next(userProcessContainer);
    }//GEN-LAST:event_browseAllProductsButtonActionPerformed

    private void searchProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductsButtonActionPerformed
        // TODO add your handling code here:
        if (productSearchText.getText() == " " || productSearchText.getText() == null){
            JOptionPane.showMessageDialog(this,"Enter something to search","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            ArrayList<ProductMaster> searchProductList = productCatalog.searchProduct(productSearchText.getText());
            CustomerSearchResultsJPanel panel = new CustomerSearchResultsJPanel(userProcessContainer,searchProductList, vendorCatalog);
            userProcessContainer.add("CustomerSearchResultPanel", panel);
            CardLayout card = (CardLayout)userProcessContainer.getLayout();
            card.next(userProcessContainer);
        }
    }//GEN-LAST:event_searchProductsButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseAllProductsButton;
    private javax.swing.JButton browseComputerButton;
    private javax.swing.JButton browseHardwareButton;
    private javax.swing.JButton browsePrinterButton;
    private javax.swing.JButton browseSoftwareButton;
    private javax.swing.JLabel catalogsHeadertag;
    private javax.swing.JLabel headerTag;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField productSearchText;
    private javax.swing.JButton searchProductsButton;
    private javax.swing.JLabel searchProductsLabel;
    private javax.swing.JLabel subHeaderTag;
    // End of variables declaration//GEN-END:variables
}
